

const posts = [
    {image: 'https://img.freepik.com/foto-gratis/retrato-hermoso-mujer-joven-posicion-pared-gris_231208-10760.jpg', 
    date: '29/08/2023', 
    userOwner: 'Hernandez Arturo', 
    comments: [], 
    likes: 2, 
    title: 'Persona chida', 
    category: 'Mujeres', 
    description: 'Foto de una sesion profesional en NYC'},
    {image: 'https://img.freepik.com/foto-gratis/retrato-hermoso-mujer-joven-posicion-pared-gris_231208-10760.jpg', 
    date: '29/08/2023', 
    userOwner: 'Hernandez Arturo', 
    comments: [], 
    likes: 2, 
    title: 'Persona chida', 
    category: 'Mujeres', 
    description: 'Foto de una sesion profesional en NYC'},
    {image: 'https://img.freepik.com/foto-gratis/retrato-hermoso-mujer-joven-posicion-pared-gris_231208-10760.jpg', 
    date: '29/08/2023', 
    userOwner: 'Hernandez Arturo', 
    comments: [], 
    likes: 2, 
    title: 'Persona chida', 
    category: 'Mujeres', 
    description: 'Foto de una sesion profesional en NYC'},
    {image: 'https://img.freepik.com/foto-gratis/retrato-hermoso-mujer-joven-posicion-pared-gris_231208-10760.jpg', 
    date: '29/08/2023', 
    userOwner: 'Hernandez Arturo', 
    comments: [], 
    likes: 2, 
    title: 'Persona chida', 
    category: 'Mujeres', 
    description: 'Foto de una sesion profesional en NYC'},
    {image: 'https://img.freepik.com/foto-gratis/retrato-hermoso-mujer-joven-posicion-pared-gris_231208-10760.jpg', 
    date: '29/08/2023', 
    userOwner: 'Hernandez Arturo', 
    comments: [], 
    likes: 2, 
    title: 'Persona chida', 
    category: 'Mujeres', 
    description: 'Foto de una sesion profesional en NYC'},
    {image: 'https://img.freepik.com/foto-gratis/retrato-hermoso-mujer-joven-posicion-pared-gris_231208-10760.jpg', 
    date: '29/08/2023', 
    userOwner: 'Hernandez Arturo', 
    comments: [], 
    likes: 2, 
    title: 'Persona chida', 
    category: 'Mujeres', 
    description: 'Foto de una sesion profesional en NYC'},
    {image: 'https://img.freepik.com/foto-gratis/retrato-hermoso-mujer-joven-posicion-pared-gris_231208-10760.jpg', 
    date: '29/08/2023', 
    userOwner: 'Hernandez Arturo', 
    comments: [], 
    likes: 2, 
    title: 'Persona chida', 
    category: 'Mujeres', 
    description: 'Foto de una sesion profesional en NYC'},
    {image: 'https://img.freepik.com/foto-gratis/retrato-hermoso-mujer-joven-posicion-pared-gris_231208-10760.jpg', 
    date: '29/08/2023', 
    userOwner: 'Hernandez Arturo', 
    comments: [], 
    likes: 2, 
    title: 'Persona chida', 
    category: 'Mujeres', 
    description: 'Foto de una sesion profesional en NYC'},
    {image: 'https://img.freepik.com/foto-gratis/retrato-hermoso-mujer-joven-posicion-pared-gris_231208-10760.jpg', 
    date: '29/08/2023', 
    userOwner: 'Hernandez Arturo', 
    comments: [], 
    likes: 2, 
    title: 'Persona chida', 
    category: 'Mujeres', 
    description: 'Foto de una sesion profesional en NYC'},
    {image: 'https://img.freepik.com/foto-gratis/retrato-hermoso-mujer-joven-posicion-pared-gris_231208-10760.jpg', 
    date: '29/08/2023', 
    userOwner: 'Hernandez Arturo', 
    comments: [], 
    likes: 2, 
    title: 'Persona chida', 
    category: 'Mujeres', 
    description: 'Foto de una sesion profesional en NYC'},
    {image: 'https://img.freepik.com/foto-gratis/retrato-hermoso-mujer-joven-posicion-pared-gris_231208-10760.jpg', 
    date: '29/08/2023', 
    userOwner: 'Hernandez Arturo', 
    comments: [], 
    likes: 2, 
    title: 'Persona chida', 
    category: 'Mujeres', 
    description: 'Foto de una sesion profesional en NYC'},
    {image: 'https://img.freepik.com/foto-gratis/retrato-hermoso-mujer-joven-posicion-pared-gris_231208-10760.jpg', 
    date: '29/08/2023', 
    userOwner: 'Hernandez Arturo', 
    comments: [], 
    likes: 2, 
    title: 'Persona chida', 
    category: 'Mujeres', 
    description: 'Foto de una sesion profesional en NYC'},
    {image: 'https://img.freepik.com/foto-gratis/retrato-hermoso-mujer-joven-posicion-pared-gris_231208-10760.jpg', 
    date: '29/08/2023', 
    userOwner: 'Hernandez Arturo', 
    comments: [], 
    likes: 2, 
    title: 'Persona chida', 
    category: 'Mujeres', 
    description: 'Foto de una sesion profesional en NYC'},
    {image: 'https://img.freepik.com/foto-gratis/retrato-hermoso-mujer-joven-posicion-pared-gris_231208-10760.jpg', 
    date: '29/08/2023', 
    userOwner: 'Hernandez Arturo', 
    comments: [], 
    likes: 2, 
    title: 'Persona chida', 
    category: 'Mujeres', 
    description: 'Foto de una sesion profesional en NYC'},
    {image: 'https://img.freepik.com/foto-gratis/retrato-hermoso-mujer-joven-posicion-pared-gris_231208-10760.jpg', 
    date: '29/08/2023', 
    userOwner: 'Hernandez Arturo', 
    comments: [], 
    likes: 2, 
    title: 'Persona chida', 
    category: 'Mujeres', 
    description: 'Foto de una sesion profesional en NYC'},
    {image: 'https://img.freepik.com/foto-gratis/retrato-hermoso-mujer-joven-posicion-pared-gris_231208-10760.jpg', 
    date: '29/08/2023', 
    userOwner: 'Hernandez Arturo', 
    comments: [], 
    likes: 2, 
    title: 'Persona chida', 
    category: 'Mujeres', 
    description: 'Foto de una sesion profesional en NYC'},
    {image: 'https://img.freepik.com/foto-gratis/retrato-hermoso-mujer-joven-posicion-pared-gris_231208-10760.jpg', 
    date: '29/08/2023', 
    userOwner: 'Hernandez Arturo', 
    comments: [], 
    likes: 2, 
    title: 'Persona chida', 
    category: 'Mujeres', 
    description: 'Foto de una sesion profesional en NYC'},
    {image: 'https://img.freepik.com/foto-gratis/retrato-hermoso-mujer-joven-posicion-pared-gris_231208-10760.jpg', 
    date: '29/08/2023', 
    userOwner: 'Hernandez Arturo', 
    comments: [], 
    likes: 2, 
    title: 'Persona chida', 
    category: 'Mujeres', 
    description: 'Foto de una sesion profesional en NYC'},
    {image: 'https://img.freepik.com/foto-gratis/retrato-hermoso-mujer-joven-posicion-pared-gris_231208-10760.jpg', 
    date: '29/08/2023', 
    userOwner: 'Hernandez Arturo', 
    comments: [], 
    likes: 2, 
    title: 'Persona chida', 
    category: 'Mujeres', 
    description: 'Foto de una sesion profesional en NYC'},
    {image: 'https://img.freepik.com/foto-gratis/retrato-hermoso-mujer-joven-posicion-pared-gris_231208-10760.jpg', 
    date: '29/08/2023', 
    userOwner: 'Hernandez Arturo', 
    comments: [], 
    likes: 2, 
    title: 'Persona chida', 
    category: 'Mujeres', 
    description: 'Foto de una sesion profesional en NYC'},
    {image: 'https://img.freepik.com/foto-gratis/retrato-hermoso-mujer-joven-posicion-pared-gris_231208-10760.jpg', 
    date: '29/08/2023', 
    userOwner: 'Hernandez Arturo', 
    comments: [], 
    likes: 2, 
    title: 'Persona chida', 
    category: 'Mujeres', 
    description: 'Foto de una sesion profesional en NYC'},
    {image: 'https://img.freepik.com/foto-gratis/retrato-hermoso-mujer-joven-posicion-pared-gris_231208-10760.jpg', 
    date: '29/08/2023', 
    userOwner: 'Hernandez Arturo', 
    comments: [], 
    likes: 2, 
    title: 'Persona chida', 
    category: 'Mujeres', 
    description: 'Foto de una sesion profesional en NYC'},
    {image: 'https://img.freepik.com/foto-gratis/retrato-hermoso-mujer-joven-posicion-pared-gris_231208-10760.jpg', 
    date: '29/08/2023', 
    userOwner: 'Hernandez Arturo', 
    comments: [], 
    likes: 2, 
    title: 'Persona chida', 
    category: 'Mujeres', 
    description: 'Foto de una sesion profesional en NYC'},
    {image: 'https://img.freepik.com/foto-gratis/retrato-hermoso-mujer-joven-posicion-pared-gris_231208-10760.jpg', 
    date: '29/08/2023', 
    userOwner: 'Hernandez Arturo', 
    comments: [], 
    likes: 2, 
    title: 'Persona chida', 
    category: 'Mujeres', 
    description: 'Foto de una sesion profesional en NYC'},
    {image: 'https://img.freepik.com/foto-gratis/retrato-hermoso-mujer-joven-posicion-pared-gris_231208-10760.jpg', 
    date: '29/08/2023', 
    userOwner: 'Hernandez Arturo', 
    comments: [], 
    likes: 2, 
    title: 'Persona chida', 
    category: 'Mujeres', 
    description: 'Foto de una sesion profesional en NYC'},
    {image: 'https://img.freepik.com/foto-gratis/retrato-hermoso-mujer-joven-posicion-pared-gris_231208-10760.jpg', 
    date: '29/08/2023', 
    userOwner: 'Hernandez Arturo', 
    comments: [], 
    likes: 2, 
    title: 'Persona chida', 
    category: 'Mujeres', 
    description: 'Foto de una sesion profesional en NYC'},
    {image: 'https://img.freepik.com/foto-gratis/retrato-hermoso-mujer-joven-posicion-pared-gris_231208-10760.jpg', 
    date: '29/08/2023', 
    userOwner: 'Hernandez Arturo', 
    comments: [], 
    likes: 2, 
    title: 'Persona chida', 
    category: 'Mujeres', 
    description: 'Foto de una sesion profesional en NYC'},
    {image: 'https://img.freepik.com/foto-gratis/retrato-hermoso-mujer-joven-posicion-pared-gris_231208-10760.jpg', 
    date: '29/08/2023', 
    userOwner: 'Hernandez Arturo', 
    comments: [], 
    likes: 2, 
    title: 'Persona chida', 
    category: 'Mujeres', 
    description: 'Foto de una sesion profesional en NYC'},
    {image: 'https://img.freepik.com/foto-gratis/retrato-hermoso-mujer-joven-posicion-pared-gris_231208-10760.jpg', 
    date: '29/08/2023', 
    userOwner: 'Hernandez Arturo', 
    comments: [], 
    likes: 2, 
    title: 'Persona chida', 
    category: 'Mujeres', 
    description: 'Foto de una sesion profesional en NYC'},
    {image: 'https://img.freepik.com/foto-gratis/retrato-hermoso-mujer-joven-posicion-pared-gris_231208-10760.jpg', 
    date: '29/08/2023', 
    userOwner: 'Hernandez Arturo', 
    comments: [], 
    likes: 2, 
    title: 'Persona chida', 
    category: 'Mujeres', 
    description: 'Foto de una sesion profesional en NYC'},
    {image: 'https://img.freepik.com/foto-gratis/retrato-hermoso-mujer-joven-posicion-pared-gris_231208-10760.jpg', 
    date: '29/08/2023', 
    userOwner: 'Hernandez Arturo', 
    comments: [], 
    likes: 2, 
    title: 'Persona chida', 
    category: 'Mujeres', 
    description: 'Foto de una sesion profesional en NYC'},
    {image: 'https://img.freepik.com/foto-gratis/retrato-hermoso-mujer-joven-posicion-pared-gris_231208-10760.jpg', 
    date: '29/08/2023', 
    userOwner: 'Hernandez Arturo', 
    comments: [], 
    likes: 2, 
    title: 'Persona chida', 
    category: 'Mujeres', 
    description: 'Foto de una sesion profesional en NYC'},
    {image: 'https://img.freepik.com/foto-gratis/retrato-hermoso-mujer-joven-posicion-pared-gris_231208-10760.jpg', 
    date: '29/08/2023', 
    userOwner: 'Hernandez Arturo', 
    comments: [], 
    likes: 2, 
    title: 'Persona chida', 
    category: 'Mujeres', 
    description: 'Foto de una sesion profesional en NYC'},
    {image: 'https://img.freepik.com/foto-gratis/retrato-hermoso-mujer-joven-posicion-pared-gris_231208-10760.jpg', 
    date: '29/08/2023', 
    userOwner: 'Hernandez Arturo', 
    comments: [], 
    likes: 2, 
    title: 'Persona chida', 
    category: 'Mujeres', 
    description: 'Foto de una sesion profesional en NYC'},
    {image: 'https://img.freepik.com/foto-gratis/retrato-hermoso-mujer-joven-posicion-pared-gris_231208-10760.jpg', 
    date: '29/08/2023', 
    userOwner: 'Hernandez Arturo', 
    comments: [], 
    likes: 2, 
    title: 'Persona chida', 
    category: 'Mujeres', 
    description: 'Foto de una sesion profesional en NYC'},
    {image: 'https://img.freepik.com/foto-gratis/retrato-hermoso-mujer-joven-posicion-pared-gris_231208-10760.jpg', 
    date: '29/08/2023', 
    userOwner: 'Hernandez Arturo', 
    comments: [], 
    likes: 2, 
    title: 'Persona chida', 
    category: 'Mujeres', 
    description: 'Foto de una sesion profesional en NYC'},
    {image: 'https://img.freepik.com/foto-gratis/retrato-hermoso-mujer-joven-posicion-pared-gris_231208-10760.jpg', 
    date: '29/08/2023', 
    userOwner: 'Hernandez Arturo', 
    comments: [], 
    likes: 2, 
    title: 'Persona chida', 
    category: 'Mujeres', 
    description: 'Foto de una sesion profesional en NYC'},
    {image: 'https://img.freepik.com/foto-gratis/retrato-hermoso-mujer-joven-posicion-pared-gris_231208-10760.jpg', 
    date: '29/08/2023', 
    userOwner: 'Hernandez Arturo', 
    comments: [], 
    likes: 2, 
    title: 'Persona chida', 
    category: 'Mujeres', 
    description: 'Foto de una sesion profesional en NYC'},
    {image: 'https://img.freepik.com/foto-gratis/retrato-hermoso-mujer-joven-posicion-pared-gris_231208-10760.jpg', 
    date: '29/08/2023', 
    userOwner: 'Hernandez Arturo', 
    comments: [], 
    likes: 2, 
    title: 'Persona chida', 
    category: 'Mujeres', 
    description: 'Foto de una sesion profesional en NYC'},
    {image: 'https://img.freepik.com/foto-gratis/retrato-hermoso-mujer-joven-posicion-pared-gris_231208-10760.jpg', 
    date: '29/08/2023', 
    userOwner: 'Hernandez Arturo', 
    comments: [], 
    likes: 2, 
    title: 'Persona chida', 
    category: 'Mujeres', 
    description: 'Foto de una sesion profesional en NYC'},
    {image: 'https://img.freepik.com/foto-gratis/retrato-hermoso-mujer-joven-posicion-pared-gris_231208-10760.jpg', 
    date: '29/08/2023', 
    userOwner: 'Hernandez Arturo', 
    comments: [], 
    likes: 2, 
    title: 'Persona chida', 
    category: 'Mujeres', 
    description: 'Foto de una sesion profesional en NYC'},
    {image: 'https://img.freepik.com/foto-gratis/retrato-hermoso-mujer-joven-posicion-pared-gris_231208-10760.jpg', 
    date: '29/08/2023', 
    userOwner: 'Hernandez Arturo', 
    comments: [], 
    likes: 2, 
    title: 'Persona chida', 
    category: 'Mujeres', 
    description: 'Foto de una sesion profesional en NYC'},
    {image: 'https://img.freepik.com/foto-gratis/retrato-hermoso-mujer-joven-posicion-pared-gris_231208-10760.jpg', 
    date: '29/08/2023', 
    userOwner: 'Hernandez Arturo', 
    comments: [], 
    likes: 2, 
    title: 'Persona chida', 
    category: 'Mujeres', 
    description: 'Foto de una sesion profesional en NYC'},
    {image: 'https://img.freepik.com/foto-gratis/retrato-hermoso-mujer-joven-posicion-pared-gris_231208-10760.jpg', 
    date: '29/08/2023', 
    userOwner: 'Hernandez Arturo', 
    comments: [], 
    likes: 2, 
    title: 'Persona chida', 
    category: 'Mujeres', 
    description: 'Foto de una sesion profesional en NYC'},
    {image: 'https://img.freepik.com/foto-gratis/retrato-hermoso-mujer-joven-posicion-pared-gris_231208-10760.jpg', 
    date: '29/08/2023', 
    userOwner: 'Hernandez Arturo', 
    comments: [], 
    likes: 2, 
    title: 'Persona chida', 
    category: 'Mujeres', 
    description: 'Foto de una sesion profesional en NYC'},
    {image: 'https://img.freepik.com/foto-gratis/retrato-hermoso-mujer-joven-posicion-pared-gris_231208-10760.jpg', 
    date: '29/08/2023', 
    userOwner: 'Hernandez Arturo', 
    comments: [], 
    likes: 2, 
    title: 'Persona chida', 
    category: 'Mujeres', 
    description: 'Foto de una sesion profesional en NYC'},
    {image: 'https://img.freepik.com/foto-gratis/retrato-hermoso-mujer-joven-posicion-pared-gris_231208-10760.jpg', 
    date: '29/08/2023', 
    userOwner: 'Hernandez Arturo', 
    comments: [], 
    likes: 2, 
    title: 'Persona chida', 
    category: 'Mujeres', 
    description: 'Foto de una sesion profesional en NYC'},
    {image: 'https://img.freepik.com/foto-gratis/retrato-hermoso-mujer-joven-posicion-pared-gris_231208-10760.jpg', 
    date: '29/08/2023', 
    userOwner: 'Hernandez Arturo', 
    comments: [], 
    likes: 2, 
    title: 'Persona chida', 
    category: 'Mujeres', 
    description: 'Foto de una sesion profesional en NYC'},
    {image: 'https://img.freepik.com/foto-gratis/retrato-hermoso-mujer-joven-posicion-pared-gris_231208-10760.jpg', 
    date: '29/08/2023', 
    userOwner: 'Hernandez Arturo', 
    comments: [], 
    likes: 2, 
    title: 'Persona chida', 
    category: 'Mujeres', 
    description: 'Foto de una sesion profesional en NYC'},
]

export default posts